theme: jekyll-theme-minimal # You can choose any theme you like
title: "Chikadibia Ezeh - Data Engineer"
profile_picture: https://github.com/Chikadibia-E/portfolio/blob/main/workprofile.png
cover_picture: https://github.com/Chikadibia-E/portfolio/blob/main/work_profile_cover.png
